DataBiosphere/welder

.gitignore
README.md
core/src/main/scala/org/broadinstitute/dsp/workbench/welder/Crc32c.scala
core/src/main/scala/org/broadinstitute/dsp/workbench/welder/JsonCodec.scala
core/src/main/scala/org/broadinstitute/dsp/workbench/welder/model.scala
core/src/main/scala/org/broadinstitute/dsp/workbench/welder/package.scala
core/src/test/scala/org/broadinstitute/dsp/workbench/welder/Generators.scala
core/src/test/scala/org/broadinstitute/dsp/workbench/welder/JsonCodecSpec.scala
core/src/test/scala/org/broadinstitute/dsp/workbench/welder/PackageSpec.scala
project/Dependencies.scala
project/build.properties
server/src/main/resources/api-docs.yaml
server/src/main/resources/reference.conf
server/src/main/scala/org/broadinstitute/dsp/workbench/welder/server/Config.scala
server/src/main/scala/org/broadinstitute/dsp/workbench/welder/server/Main.scala
server/src/main/scala/org/broadinstitute/dsp/workbench/welder/server/ObjectService.scala
server/src/main/scala/org/broadinstitute/dsp/workbench/welder/server/StorageLinksService.scala
server/src/main/scala/org/broadinstitute/dsp/workbench/welder/server/WelderApp.scala
server/src/test/scala/org/broadinstitute/dsp/workbench/welder/server/ConfigSpec.scala
server/src/test/scala/org/broadinstitute/dsp/workbench/welder/server/ObjectServiceSpec.scala
server/src/test/scala/org/broadinstitute/dsp/workbench/welder/server/StorageLinksServiceSpec.scala

* better json decoding error in api response
* a few bug fixes
* Add delete api
* Make server port configurable

refactor and add delete api

---

README.md
core/src/main/scala/org/broadinstitute/dsp/workbench/welder/JsonCodec.scala
core/src/main/scala/org/broadinstitute/dsp/workbench/welder/model.scala
project/Dependencies.scala
server/src/main/resources/api-docs.yaml
server/src/main/scala/org/broadinstitute/dsp/workbench/welder/server/ObjectService.scala

minor clean up
```
~ curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' localhost:8081/objects -d '{"action" : "localize",  "entries": [{ "sourceUri": "gs://qi-test/welder-test_nb.ipynb", "localDestinationPath": "/Users/jcanas/test" }] }'
{"errorMessage":"DecodingFailure(Path should be relative, List(DownField(localDestinationPath), DownArray, DownField(entries)))","errorCode":null}%
```

doc update

---

server/src/main/resources/api-docs.yaml

This affects the swagger codegen models
@jmthibault79

Entry -> LocalizationEntry for more specificity

---

server/src/main/resources/logback.xml

Tested locally in docker image

IA-1104 move application.log to working directory

---

core/src/main/scala/org/broadinstitute/dsp/workbench/welder/package.scala
core/src/main/scala/org/broadinstitute/dsp/workbench/welder/welderExceptions.scala
server/src/main/resources/api-docs.yaml
server/src/main/resources/reference.conf
server/src/main/scala/org/broadinstitute/dsp/workbench/welder/server/ObjectService.scala
server/src/main/scala/org/broadinstitute/dsp/workbench/welder/server/WelderApp.scala
server/src/test/scala/org/broadinstitute/dsp/workbench/welder/server/ConfigSpec.scala
server/src/test/scala/org/broadinstitute/dsp/workbench/welder/server/ObjectServiceSpec.scala

* acquireLock will return 409 when lock is held by other; 204 when successfully acquire lock
* move cache json file to .welder dir

change lock response

---

core/src/main/scala/org/broadinstitute/dsp/workbench/welder/BackgroundTask.scala
core/src/main/scala/org/broadinstitute/dsp/workbench/welder/GoogleStorageAlg.scala
core/src/main/scala/org/broadinstitute/dsp/workbench/welder/GoogleStorageInterp.scala
core/src/main/scala/org/broadinstitute/dsp/workbench/welder/model.scala
project/Dependencies.scala
project/build.properties
project/plugins.sbt
server/src/main/scala/org/broadinstitute/dsp/workbench/welder/server/Main.scala

1. upgrade scalafmt to 2.0.3
2. run scalafmt
3. upgrade http4s to 0.20.9
4. downgrade sbt to 1.2.8

miscellaneous changes

---

server/src/main/resources/reference.conf
server/src/main/scala/org/broadinstitute/dsp/workbench/welder/server/Config.scala
server/src/main/scala/org/broadinstitute/dsp/workbench/welder/server/Main.scala
server/src/main/scala/org/broadinstitute/dsp/workbench/welder/server/StorageLinksService.scala
server/src/test/scala/org/broadinstitute/dsp/workbench/welder/server/ConfigSpec.scala
server/src/test/scala/org/broadinstitute/dsp/workbench/welder/server/ObjectServiceSpec.scala
server/src/test/scala/org/broadinstitute/dsp/workbench/welder/server/StorageLinksApiServiceSpec.scala
server/src/test/scala/org/broadinstitute/dsp/workbench/welder/server/StorageLinksServiceSpec.scala

https://broadworkbench.atlassian.net/browse/IA-1339
Tested with Azmina's terra-ui branch

IA-1339 persist WORKSPACE_BUCKET

---

core/src/main/scala/org/broadinstitute/dsp/workbench/welder/BackgroundTask.scala
core/src/main/scala/org/broadinstitute/dsp/workbench/welder/GoogleStorageAlg.scala
core/src/main/scala/org/broadinstitute/dsp/workbench/welder/GoogleStorageInterp.scala
core/src/main/scala/org/broadinstitute/dsp/workbench/welder/package.scala
core/src/test/scala/org/broadinstitute/dsp/workbench/welder/PackageSpec.scala
server/src/main/resources/reference.conf
server/src/main/scala/org/broadinstitute/dsp/workbench/welder/server/Config.scala
server/src/main/scala/org/broadinstitute/dsp/workbench/welder/server/Main.scala
server/src/main/scala/org/broadinstitute/dsp/workbench/welder/server/ShutdownService.scala
server/src/test/scala/org/broadinstitute/dsp/workbench/welder/server/ConfigSpec.scala
server/src/test/scala/org/broadinstitute/dsp/workbench/welder/server/ObjectServiceSpec.scala
server/src/test/scala/org/broadinstitute/dsp/workbench/welder/server/ShutdownServiceSpec.scala
server/src/test/scala/org/broadinstitute/dsp/workbench/welder/server/StorageLinksApiServiceSpec.scala
server/src/test/scala/org/broadinstitute/dsp/workbench/welder/server/StorageLinksServiceSpec.scala

https://broadworkbench.atlassian.net/browse/IA-1707

IA-1707 upload metadata to gcs

---

core/src/main/scala/org/broadinstitute/dsp/workbench/welder/GoogleStorageInterp.scala
project/Dependencies.scala
server/src/main/scala/org/broadinstitute/dsp/workbench/welder/server/Main.scala

don't use getContent which loads the entire notebook into memory

[IA-2090] don't use getContent

---

core/src/main/scala/org/broadinstitute/dsp/workbench/welder/BackgroundTask.scala
core/src/main/scala/org/broadinstitute/dsp/workbench/welder/GoogleStorageAlg.scala
core/src/main/scala/org/broadinstitute/dsp/workbench/welder/GoogleStorageInterp.scala
core/src/main/scala/org/broadinstitute/dsp/workbench/welder/package.scala
core/src/test/scala/org/broadinstitute/dsp/workbench/welder/GoogleStorageInterpSpec.scala
core/src/test/scala/org/broadinstitute/dsp/workbench/welder/PackageSpec.scala
project/Dependencies.scala
server/src/main/scala/org/broadinstitute/dsp/workbench/welder/server/ShutdownService.scala
server/src/main/scala/org/broadinstitute/dsp/workbench/welder/server/WelderApp.scala
server/src/test/scala/org/broadinstitute/dsp/workbench/welder/server/ObjectServiceSpec.scala
server/src/test/scala/org/broadinstitute/dsp/workbench/welder/server/ShutdownServiceSpec.scala

https://broadworkbench.atlassian.net/browse/IA-2118
https://broadworkbench.atlassian.net/browse/IA-2120
Some diff is from scalafmt

IA-2118 IA-2120 use stream upload

---

.github/workflows/createPullRequest.yml
.github/workflows/trivy.yml
project/Settings.scala

1. Enable trivy..change borrowed from @dinvlad 's PR
2. Update base image for welder to fix trivy warnings.
3. Add action for sending PR to leonardo (this action isn't really tested yet...but if it doesn't work, I'll have follow-up PRs to fix it)

IA-2343 enable trivy

---

.github/workflows/createPullRequest.yml

It should be working now..example https://github.com/DataBiosphere/leonardo/pull/1838

[no ticket] try fixing github workflow for creating leonardo PR

---

project/Settings.scala

https://broadworkbench.atlassian.net/browse/IA-2876

IA-2876 use blessed image

---

README.md
cloudbuild.yaml

add env var needed for cloud build

[IA-2653] Add missing env vars for CI

---

core/src/test/scala/org/broadinstitute/dsp/workbench/welder/BackgroundTaskSpec.scala

[IA-2653] fix cloud build

---

core/src/main/scala/org/broadinstitute/dsp/workbench/welder/BackgroundTask.scala
core/src/main/scala/org/broadinstitute/dsp/workbench/welder/Crc32c.scala
core/src/main/scala/org/broadinstitute/dsp/workbench/welder/GoogleStorageAlg.scala
core/src/main/scala/org/broadinstitute/dsp/workbench/welder/GoogleStorageInterp.scala
core/src/main/scala/org/broadinstitute/dsp/workbench/welder/JsonCodec.scala
core/src/main/scala/org/broadinstitute/dsp/workbench/welder/package.scala
core/src/test/scala/org/broadinstitute/dsp/workbench/welder/BackgroundTaskSpec.scala
core/src/test/scala/org/broadinstitute/dsp/workbench/welder/GoogleStorageInterpSpec.scala
core/src/test/scala/org/broadinstitute/dsp/workbench/welder/PackageSpec.scala
core/src/test/scala/org/broadinstitute/dsp/workbench/welder/StorageLinksInterpSpec.scala
core/src/test/scala/org/broadinstitute/dsp/workbench/welder/WelderTestSuite.scala
project/Dependencies.scala
server/src/main/scala/org/broadinstitute/dsp/workbench/welder/server/Main.scala
server/src/main/scala/org/broadinstitute/dsp/workbench/welder/server/ObjectService.scala
server/src/main/scala/org/broadinstitute/dsp/workbench/welder/server/ShutdownService.scala
server/src/main/scala/org/broadinstitute/dsp/workbench/welder/server/StorageLinksService.scala
server/src/main/scala/org/broadinstitute/dsp/workbench/welder/server/WelderApp.scala
server/src/main/scala/org/broadinstitute/dsp/workbench/welder/server/WelderService.scala
server/src/main/scala/org/broadinstitute/dsp/workbench/welder/server/package.scala
server/src/test/scala/org/broadinstitute/dsp/workbench/welder/server/ObjectServiceSpec.scala
server/src/test/scala/org/broadinstitute/dsp/workbench/welder/server/ShutdownServiceSpec.scala
server/src/test/scala/org/broadinstitute/dsp/workbench/welder/server/StatusServiceSpec.scala
server/src/test/scala/org/broadinstitute/dsp/workbench/welder/server/StorageLinksApiServiceSpec.scala
server/src/test/scala/org/broadinstitute/dsp/workbench/welder/server/StorageLinksServiceSpec.scala

while investigating https://broadworkbench.atlassian.net/browse/IA-3222, I notice welder hasn't been updated for a while in terms of dependencies. So this PR mostly just upgrade it to use cats-effect 3

[no ticket] upgrade to cats-effect 3

---

core/src/main/scala/org/broadinstitute/dsp/workbench/welder/BackgroundTask.scala
core/src/main/scala/org/broadinstitute/dsp/workbench/welder/GoogleStorageAlg.scala
core/src/main/scala/org/broadinstitute/dsp/workbench/welder/GoogleStorageInterp.scala
server/src/test/scala/org/broadinstitute/dsp/workbench/welder/server/ObjectServiceSpec.scala

See corresponding UI PR for testing https://github.com/DataBiosphere/terra-ui/pull/2810

[IA-3209] Handle when a user does not want their file synced

---

project/Dependencies.scala
server/src/main/resources/reference.conf
server/src/test/scala/org/broadinstitute/dsp/workbench/welder/server/ConfigSpec.scala

We're still seeing outdated cache issue. Make flushing even more frequent and bump a few dependencies for now

SUP-643  bump a few dependencies

---

project/Settings.scala
server/src/main/resources/logback.xml
server/src/test/scala/org/broadinstitute/dsp/workbench/welder/server/ShutdownServiceSpec.scala

Hiding the file. How do I go about testing this change?

[IA-3425] Hide Entrypoint.out and welder.log files in Rstudio Directory

---

core/README.md
core/src/main/scala/org/broadinstitute/dsp/workbench/welder/AzureStorageInterp.scala
core/src/main/scala/org/broadinstitute/dsp/workbench/welder/CloudStorageAlg.scala
core/src/main/scala/org/broadinstitute/dsp/workbench/welder/GoogleStorageInterp.scala
core/src/main/scala/org/broadinstitute/dsp/workbench/welder/MiscHttpClientAlg.scala
core/src/main/scala/org/broadinstitute/dsp/workbench/welder/MiscHttpClientInterp.scala
core/src/main/scala/org/broadinstitute/dsp/workbench/welder/package.scala
core/src/test/scala/org/broadinstitute/dsp/workbench/welder/GoogleStorageInterpSpec.scala
core/src/test/scala/org/broadinstitute/dsp/workbench/welder/MiscHttpClientInterpSpec.scala
core/src/test/scala/org/broadinstitute/dsp/workbench/welder/PackageSpec.scala
core/src/test/scala/org/broadinstitute/dsp/workbench/welder/mocks.scala
project/Dependencies.scala
server/src/main/resources/reference.conf
server/src/main/scala/org/broadinstitute/dsp/workbench/welder/server/BackgroundTask.scala
server/src/main/scala/org/broadinstitute/dsp/workbench/welder/server/Config.scala
server/src/main/scala/org/broadinstitute/dsp/workbench/welder/server/Main.scala
server/src/main/scala/org/broadinstitute/dsp/workbench/welder/server/ObjectService.scala
server/src/main/scala/org/broadinstitute/dsp/workbench/welder/server/ShutdownService.scala
server/src/main/scala/org/broadinstitute/dsp/workbench/welder/server/StorageLinksService.scala
server/src/main/scala/org/broadinstitute/dsp/workbench/welder/server/package.scala
server/src/test/resources/reference.conf
server/src/test/scala/org/broadinstitute/dsp/workbench/welder/server/BackgroundTaskSpec.scala
server/src/test/scala/org/broadinstitute/dsp/workbench/welder/server/ConfigSpec.scala
server/src/test/scala/org/broadinstitute/dsp/workbench/welder/server/ObjectServiceSpec.scala
server/src/test/scala/org/broadinstitute/dsp/workbench/welder/server/ShutdownServiceSpec.scala
server/src/test/scala/org/broadinstitute/dsp/workbench/welder/server/StorageLinksApiServiceSpec.scala
server/src/test/scala/org/broadinstitute/dsp/workbench/welder/server/StorageLinksServiceSpec.scala

https://broadworkbench.atlassian.net/browse/IA-3512
Once https://github.com/DataBiosphere/leonardo/pull/2804's tests are passing, this PR should be ready to be merged

IA-3512 Support Azure

---

.github/workflows/createPullRequest.yml
server/src/main/resources/reference.conf

https://broadworkbench.atlassian.net/browse/IA-3625

IA-3625 add CI for publishing welder image

---

.github/workflows/createPullRequest.yml

Add missing environment variable for publishing image to ACR

IA-3655 add missing env

---

.github/workflows/createPullRequest.yml
.github/workflows/publishToAcr.yml
project/Settings.scala

https://broadworkbench.atlassian.net/browse/IA-3655
Tested...See a successful run https://github.com/DataBiosphere/welder/runs/7862186814?check_suite_focus=true

IA-3655 Fix publishing image to ACR

---

README.md
core/src/main/scala/org/broadinstitute/dsp/workbench/welder/AzureStorageInterp.scala
server/src/main/resources/reference.conf
server/src/main/scala/org/broadinstitute/dsp/workbench/welder/server/ObjectService.scala
server/src/test/resources/reference.conf
server/src/test/scala/org/broadinstitute/dsp/workbench/welder/server/ConfigSpec.scala
server/src/test/scala/org/broadinstitute/dsp/workbench/welder/server/ObjectServiceSpec.scala

Related Leo PR https://github.com/DataBiosphere/leonardo/pull/2845

IA-3681 Fix renaming bug for Azure

---

.github/workflows/merge-prs.yml

Same GHA as for leonardo to help with dependencies update as we do not touch this repo very often and might end up with a lot of depnedencies update PRs at once

[IA-4556] add GHA to combine dependency update PRs

---

.github/workflows/trivy.yml
project/Dependencies.scala
project/Settings.scala
server/src/main/resources/logback.xml
server/src/test/resources/reference.conf

https://precisionmedicineinitiative.atlassian.net/browse/RW-12258
1. We're missing lots of welder logs in cloud logging. This change should make it so that all logs are appended to `CONSOLE` as well
2. Using async-appender similar to what @rtitle did for Leo in https://github.com/DataBiosphere/leonardo/blob/f4e2bf85458be858129b40f1d3ec962bc12015df/http/src/main/resources/logback.xml#L30

RW-12258 Update logback

---

.github/workflows/trivy.yml
.github/workflows/unit_test.yml
core/src/main/scala/org/broadinstitute/dsp/workbench/welder/MiscHttpClientAlg.scala
core/src/main/scala/org/broadinstitute/dsp/workbench/welder/MiscHttpClientInterp.scala
core/src/test/scala/org/broadinstitute/dsp/workbench/welder/MiscHttpClientInterpSpec.scala
server/src/main/resources/reference.conf
server/src/test/resources/reference.conf
server/src/test/scala/org/broadinstitute/dsp/workbench/welder/server/ConfigSpec.scala

Related: https://github.com/DataBiosphere/leonardo/pull/4832

[TOAZ-372] Make Azure management url configurable
